name: Bug Report
description: "Report a bug or issue with Icons8-Collector."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following to help us resolve your issue faster.
  - type: textarea
    attributes:
      label: Bug Title
      description: "A short, clear summary of the bug."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem Description
      description: "Describe the bug clearly. What did you expect to happen? What actually happened? When does it occur? (always / sometimes / specific case)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: "Provide exact steps so the bug can be reproduced."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual vs Expected Behavior
      description: "Explain the difference between expected and actual results."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment Details
      description: "OS, Python version, Icons8-Collector version, Mode (CLI/UI/Headless)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs / Error Output
      description: "Paste any relevant logs or error messages."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Workarounds Tried
      description: "Have you tried anything to fix or bypass the issue?"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Impact & Severity
      description: "How serious is this bug? (Blocks usage/Partial/Minor)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: "Add any extra information that may help diagnose the issue."
    validations:
      required: false
